#!/bin/sh
#
# Wait until some kind of connection is made
#


start() {
    printf "Waiting for connection... "
    for i in $(seq 10); do
        if ip route | grep default &>/dev/null;
        then
            echo "OK"
            exit 0
        fi

        sleep 1
    done

    echo "Failed"
    exit 1
}

stop() {
    exit 0
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart|reload}"
        exit 1
esac

exit $?
