#!/bin/sh
#
# Start NTPd
#


start() {
    PID=$(pidof ntpd)
    if [ $? -eq 0 ];
    then
        echo "ntpd is already running (pid: $PID)"
        exit 1
    fi

    printf "Starting ntpd... "
    # First do blocking update, then start as daemon
    ntpd -n -q -N -S '/sbin/hwclock -u -w' 2>/dev/null
    printf "Current date: $(date). "
    ntpd -N -S '/sbin/hwclock -u -w'
    echo "OK"
}

stop() {
    PID=$(pidof ntpd)
    if [ $? -ne 0 ];
    then
        echo "ntpd is not running"
        exit 1
    fi

    printf "Stopping ntpd: "
    kill $PID
    echo "OK"
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart|reload}"
        exit 1
esac

exit $?
